### ISSUE TITLE
關於 Volume 的問題

### ISSUE THREAD

**Issue by luckily** [srcmesh-workshop/kubernetes-adoption-hands-on#2]
Hi @life1347 大大好~

我想請教 volume 的配置, 有規定一定要 node level 或是 pod level 或是要 remote storage?

或者是說只要有設定到 volume mount 可以跑即可?

謝謝

**Comment by life1347** [comment]
並沒有指定，但可以嘗試看看 node-level 的方式，一般生產環境上比較常用這種方式設定
